webtalk_init -webtalk_dir /home/lemeille/Bureau/TP_Systeminfo/ProjetSystemeInfo/Microproc/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/Test_BancMemoireDonnees_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr 22 12:14:47 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2c0641df-9c4f-4da3-8d12-90cdb8c5e24a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e4d5f827ec484bb0817be971ff4e0413" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3200.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114388_KB" -context "xsim\\usage"
webtalk_transmit -clientid 9228615 -regid "" -xml /home/lemeille/Bureau/TP_Systeminfo/ProjetSystemeInfo/Microproc/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/Test_BancMemoireDonnees_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/lemeille/Bureau/TP_Systeminfo/ProjetSystemeInfo/Microproc/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/Test_BancMemoireDonnees_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/lemeille/Bureau/TP_Systeminfo/ProjetSystemeInfo/Microproc/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/Test_BancMemoireDonnees_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
